import "./globals.css";
import {Navbar} from "@/components/navbar";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Navbar
            isLoggedIn={true}
            username="当前用户"
            avatarUrl="/FF14?height=32&width=32"
        />
        <main>
            {children}
        </main>
        </body>
        </html>
    )
}
